# Generated by Django 4.0.5 on 2022-06-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiusertype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_Doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_Patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
