# Generated by Django 4.0.5 on 2022-06-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiusertype', '0002_rename_is_employee_user_is_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Area',
            field=models.CharField(default='area', max_length=400),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='city', max_length=400),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='state', max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
