# Generated by Django 4.0.5 on 2022-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiusertype', '0003_user_area_user_city_user_pincode_user_profileimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(default='Success.png', upload_to='profile_images'),
        ),
    ]
