# Generated by Django 4.0.5 on 2022-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiusertype', '0004_alter_user_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_Doctor',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_Patient',
            field=models.CharField(max_length=7),
        ),
    ]
