# Generated by Django 4.0.5 on 2022-06-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiusertype', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
