# Generated by Django 4.0.5 on 2022-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='postimg',
            field=models.ImageField(default='Success.png', upload_to='post_images'),
        ),
    ]
