# Generated by Django 4.0.5 on 2022-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content_alter_post_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='draft_status',
            field=models.CharField(default='draf', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_status',
            field=models.CharField(default='pub', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='some content'),
        ),
    ]
