# Generated by Django 4.0.5 on 2022-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_status_post_draft_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredspeciality', models.CharField(max_length=25)),
                ('starttime', models.TimeField()),
                ('appointmentdate', models.DateTimeField()),
                ('patientname', models.CharField(max_length=17)),
                ('doctorname', models.CharField(max_length=17)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Appointment Recieved', 'Appointment Recieved'), ('Appointment Confirmed', 'Appointment Confirmed')], default='Appointment  Recieved', max_length=100)),
            ],
        ),
    ]
