# Generated by Django 4.0.6 on 2022-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_status_post_draft_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('appointmentdate', models.DateTimeField()),
                ('patientname', models.CharField(max_length=17)),
                ('doctorname', models.CharField(max_length=17)),
            ],
        ),
    ]
