# Generated by Django 4.0.5 on 2022-08-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
